# TODO, ADD Fedora, opensuse...
# https://docs.appdynamics.com/display/PRO45/Enterprise+Console+Requirements
- name: Install packages (Debian and Ubuntu)
  become: yes 
  apt: 
    state: present
    pkg: "{{ packages.apt }}"
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Check conflicting packages  (Debian and Ubuntu)
  become: yes 
  apt: 
    state: absent
    pkg:
     - mysql-server
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
  
- name: Install packages (Centos and RHEL)
  become: yes 
  yum:
    state: present
    name: "{{ packages.yum }}"
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat" or ansible_os_family == "Centos" or ansible_os_family == "Amazon"

- name: Check conflicting packages (Centos and RHEL)
  become: yes 
  yum:
    state: absent
    name:
     - mysql-server
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat" or ansible_os_family == "Centos" or ansible_os_family == "Amazon"

