- include: install-packages.yml

- name: copy controller reverse proxy config
  template:
    src: templates/appd-controller.conf.j2
    dest: /etc/nginx/conf.d/appd-controller.conf
  when: controller_proxy | bool
  notify: Restart nginx

- name: copy es reverse proxy config
  template:
    src: templates/appd-es.conf.j2
    dest: /etc/nginx/conf.d/appd-es.conf
  when: es_proxy | bool
  notify: Restart nginx

- name: Remove default config
  file:
    name: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart nginx

# todo selinux
#sudo yum install policycoreutils-python --nogpg
#semanage port -a -t http_port_t  -p tcp 8090
#semanage port -m -t http_port_t  -p tcp 9080
